### ISSUE TITLE
Fails on Azure Notebook 'pyodbc.Cursor' object has no attribute 'fast_executemany'

### ISSUE THREAD

**Issue by moeenuddin** [mkleehammer/pyodbc#600]
### Environment

On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python:  3.6
- pyodbc: 4.0.22, 26, 27
- OS: Linux
- DB: SQL SERVER
- driver: pyodbc

### Issue

Expected Behavior:
The same code works on Mac OS using Anacoda pyodbc: 2.0.27, python 3.6

Observed behavior:

'pyodbc.Cursor' object has no attribute 'fast_executemany'

-- Note: there was a typo in writing pyodbc version i wrote 2.0.22... instead of 4.0.22

**Comment by v-chojas** [comment]
Check pyODBC version --- `fast_executemany` was added in 4.0.18, 2.x is too old to have it.

**Comment by mkleehammer** [comment]
Closing due to lack of activity.  I would guess this has been solved by the answer above.
