### PR TITLE
Don't use PyUnicode_Encode API

### PR DESCRIPTION
**Pull request by methane**
PyUnicode_EncodeUTF8 is deprecated, and PyUnicode_EncodeUTF8(PyUnicode_AS_UNICODE(p), ...) is inefficient.

### CODE REVIEW

File: src/params.cpp [hunk 1]
```diff
@@ -1941,11 +1942,28 @@ bool ExecuteMulti(Cursor* cur, PyObject* pSql, PyObject* paramArrayObj)
...
+                    switch (enc.optenc)
+                    {
+                    case OPTENC_UTF8:
+                        bytes = PyUnicode_AsUTF8String(objCell);
+                        break;
+                    case OPTENC_UTF16:
+                        bytes = PyUnicode_AsUTF16String(objCell);
+                        break;
+                    case OPTENC_UTF16LE:
+                        bytes = PyUnicode_AsEncodedString(objCell, "utf_16_le", NULL);
```
Comment (keitherskine) [inline src/params.cpp:1955]: Minor, but it might be nice to specify the errors parameter as "strict" rather than leaving it as NULL.  Ditto for OPTENC_UTF16BE.

Comment (methane) [reply src/params.cpp:1955]: In Python/C API, `errors=NULL` means "strict" consistently, like `errors=None` in Python.
And it is little faster/efficient because Python can skip `strcmp()`, creating temporary Unicode object, or looking up error handler from registry.

Do you prefer not using the default anyway?

**Comment by fila43** [comment]
The build with python3.11 fails with: 
`src/cnxninfo.cpp:45:18: error: â€˜PyUnicode_EncodeUTF8â€™ was not declared in this scope; did you mean â€˜PyUnicode_DecodeUTF8â€™?
   45 |     Object bytes(PyUnicode_EncodeUTF8(PyUnicode_AS_UNICODE(p), PyUnicode_GET_SIZE(p), 0));
      |                  ^~~~~~~~~~~~~~~~~~~~
      |                  PyUnicode_DecodeUTF8`

The change proposed in this PR fixes this issue.

**Comment by Sitaramjaat** [comment]
133

**Comment by Sitaramjaat** [comment]
331517

**Comment by Sitaramjaat** [comment]
Mast 12
