### ISSUE TITLE
PyToCType uses internal function removed from Python 3.13

### ISSUE THREAD

**Issue by mkleehammer** [mkleehammer/pyodbc#1344]
Cannot compile using 3.13:

```
src/params.cpp: In function ‘int PyToCType(Cursor*, unsigned char**, PyObject*, ParamInfo*)’:
src/params.cpp:250:36: error: too few arguments to function ‘int _PyLong_AsByteArray(PyLongObject*, unsigned char*, size_t, int, int, int)’
  250 |             if (_PyLong_AsByteArray((PyLongObject*)absVal, pNum->val, sizeof(pNum->val), 1, 0))
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

We need to figure out how to bind Decimals without using this, I guess.

**Comment by v-chojas** [comment]
We're not the only ones affected by this regression: https://github.com/python/cpython/issues/111140
pyodbc is mentioned there along with some other projects.

**Comment by AdamWill** [comment]
it seems a public function `PyLong_AsNativeBytes` has been added to do this job, IIUC. See https://github.com/python/cpython/blob/main/Doc/c-api/long.rst for docs on it.

As the error you get - "too few arguments" - implies, the function was re-added after it was removed, but then an extra argument, `with_exceptions` (an int acting as a boolean), was added in [the same commit that introduced `PyLong_AsNativeBytes`](https://github.com/python/cpython/commit/7861dfd26a). So for the short term, I think just adding the extra arg to the call would work. For the long term probably a good idea to switch to using the new public function, though.

**Comment by AdamWill** [comment]
Sent https://github.com/mkleehammer/pyodbc/pull/1361 .
