### ISSUE TITLE
invalid conversion from ‘const char*’ to ‘char*’ @ PyUnicode_AsUTF8AndSize

### ISSUE THREAD

**Issue by ericsun2** [mkleehammer/pyodbc#466]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.7
- pyodbc: 4.0.21
- OS: Linux
- DB: any
- driver: any

### Issue

Failed to build in Python 3.7

```
  building 'pyodbc' extension
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.21 -I/export/apps/python/3.7/include/python3.7m -c src/pyodbccompat.cpp -o build/temp.linux-x86_64-3.7/src/pyodbccompat.o -Wno-write-strings
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.21 -I/export/apps/python/3.7/include/python3.7m -c src/getdata.cpp -o build/temp.linux-x86_64-3.7/src/getdata.o -Wno-write-strings
  src/getdata.cpp: In function ‘PyObject* GetDataDecimal(Cursor*, Py_ssize_t)’:
  src/getdata.cpp:405:51: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
           pch = PyUnicode_AsUTF8AndSize(result, &cch);
                                                     ^
  error: command 'gcc' failed with exit status 1
```

**Comment by gordthompson** [comment]
I got the same error as you did when I tried

```
pip install pyodbc==4.0.21
```

but it worked when I just did

```
pip install pyodbc
```

which installed the most recent version (currently 4.0.24). Is there a particular reason why you need 4.0.21?

**Comment by mkleehammer** [comment]
Closing due to no response and fixed in latest.
